name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform init ./azure-api-management

      - name: Terraform Plan
        run: terraform plan ./azure-api-management
