name: Terraform Plan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify the Terraform version you want to use

      - name: Terraform Init
        run: terraform -chdir=./azure-api-management init .

      - name: Terraform Plan
        run: terraform -chdir=./azure-api-management plan .
